project:
  type: website
  output-dir: docs

website:
  title: "Sofia Ingersoll"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts.qmd
    #  - href: resources.qmd
     #   text: Resources
  page-footer: 
    background: light
    left: 
    - "Copyright 2023, Sofia Ingersoll"
    right: 
      - icon: github
        href: https://github.com/saingersoll
format:
  html:
    theme: 
      - styles.scss
    mainfont: Nunito  
    toc: true
    page-layout: full
editor: visual
#nunito is a nice font style 
# font styles from google fonts need bold and nonbolded downloaded in order to work
      #light: quartz
     # dark: darkly
    #  - styles.scss to use style sheet for themes



