project:
  type: website
  output-dir: docs

website:
  back-to-top-navigation: true
  navbar:
    title: false
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
     # - href: projects.qmd
      #  text: Projects
      - href: posts.qmd
        text: MEDS Projects
      - href: Ingersoll_Sofia_Resume.pdf
        text: Resume
      - href: Ingersoll_Sofia_CV.pdf
        text: CV
    left:
      - text: Get in Touch!
        menu: 
        - icon: envelope
          text: Email
          href: mailto::sofia.ingersoll@outlook.com 
        - icon: linkedin
          text: LinkedIn
          href: https://www.linkedin.com/in/sofia-ingersoll-078b931b7
        - icon: github
          text: GitHub
          href: https://github.com/saingersoll
      
     #  - href: resources.qmd
     #   text: Resources
    logo: "images/personal_logot.png"
  page-footer: 
    background: light
    left: 
    - "Copyright 2023, Sofia Ingersoll"
    right: 
      - icon: github
        href: https://github.com/saingersoll

format:
  html:
    page-layout: full
    sidebar: false
    theme: 
      #light: 
      - styles.scss
     # dark: [ theme-dark.scss]
    mainfont: Roboto
    toc: true
    editor: visual
