project:
  type: website
  output-dir: docs

website:
  title: "Soap"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resources.qmd
        text: Resources
      - posts.qmd

format:
  html:
    theme:
      light: quartz
      dark: darkly
      # - styles.scss to use style sheet for themes
    css: styles.css
    mainfont: Nunito  
    toc: true
    page-layout: full
#nunito is a nice font style 
# font styles from google fonts need bold and nonbolded downloaded in order to work

editor: visual


