project:
  type: website
  output-dir: docs

website:
  back-to-top-navigation: true
  navbar:
    title: false
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
     # - href: projects.qmd
      #  text: Projects
      - href: posts.qmd
        text: MEDS Projects
      - href: Ingersoll_Sofia_Resume.pdf
        text: Resume
      - href: Ingersoll_Sofia_CV.pdf
        text: CV
    left:
      - text: Get in Touch!
        menu: 
        - icon: envelope
          text: Email
          href: mailto::sofia.ingersoll@outlook.com 
        - icon: linkedin
          text: LinkedIn
          href: https://www.linkedin.com/in/sofia-ingersoll-078b931b7
        - icon: github
          text: GitHub
          href: https://github.com/saingersoll
      
    #  - href: "https://saingersoll/saingersoll.github.io/"
     #   class: "navbar-logo"
      #  src: "./images/personal_logo.png"
       # alt: "The name 'Sofia Ingersoll' written in brown text. Below the name is an icon showing a computer with code and a cloud behind it. Beneath that reads the phrase 'Creative Strategist' in brown."
    #  - href: resources.qmd
     #   text: Resources
    logo: "images/personal_logot.png"
  page-footer: 
    background: light
    left: 
    - "Copyright 2023, Sofia Ingersoll"
    right: 
      - icon: github
        href: https://github.com/saingersoll
#format:
 # html:
  #  theme: 
   #   - styles.scss
    #mainfont: Nunito  
    #toc: true
    #page-layout: full
#editor: visual
#nunito is a nice font style 
# font styles from google fonts need bold and nonbolded downloaded in order to work
      #light: quartz
     # dark: darkly
     # - styles.scss  to use style sheet for themes


format:
  html:
    page-layout: full
    sidebar: false
    theme: 
      - styles.scss
    mainfont: Roboto
    toc: true
    editor: visual
