<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Sofia Ingersoll">

<title>Sofia Ingersoll - Spatially Distorted Signaling Wind Infrastructre</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Sofia Ingersoll</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../posts.html" rel="" target="">
 <span class="menu-text">My Blog</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools ms-auto">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-page-left">
      <h1 class="title">Spatially Distorted Signaling Wind Infrastructre</h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Sofia Ingersoll </p>
            </div>
    </div>
      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#spatially-distorted-signaling" id="toc-spatially-distorted-signaling" class="nav-link active" data-scroll-target="#spatially-distorted-signaling"><strong>Spatially Distorted Signaling:</strong></a>
  <ul class="collapse">
  <li><a href="#how-opinions-against-wind-infrastructure-delay-our-transition-to-renewable-energy" id="toc-how-opinions-against-wind-infrastructure-delay-our-transition-to-renewable-energy" class="nav-link" data-scroll-target="#how-opinions-against-wind-infrastructure-delay-our-transition-to-renewable-energy">How Opinions Against Wind Infrastructure Delay Our Transition to Renewable Energy</a>
  <ul class="collapse">
  <li><a href="#main-takeaways" id="toc-main-takeaways" class="nav-link" data-scroll-target="#main-takeaways">Main Takeaways:</a></li>
  <li><a href="#loading-libraries" id="toc-loading-libraries" class="nav-link" data-scroll-target="#loading-libraries">Loading Libraries</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#read-in-the-data" id="toc-read-in-the-data" class="nav-link" data-scroll-target="#read-in-the-data">Read in the Data</a></li>
  <li><a href="#initial-visualization-of-the-data" id="toc-initial-visualization-of-the-data" class="nav-link" data-scroll-target="#initial-visualization-of-the-data">Initial Visualization of the Data</a></li>
  <li><a href="#linear-regression-models" id="toc-linear-regression-models" class="nav-link" data-scroll-target="#linear-regression-models">Linear Regression Models</a>
  <ul class="collapse">
  <li><a href="#variables-of-interest" id="toc-variables-of-interest" class="nav-link" data-scroll-target="#variables-of-interest">Variables of Interest:</a></li>
  <li><a href="#determining-variable-assignments-for-ols" id="toc-determining-variable-assignments-for-ols" class="nav-link" data-scroll-target="#determining-variable-assignments-for-ols">Determining Variable Assignments for OLS</a>
  <ul class="collapse">
  <li><a href="#redefining-status-as-a-binary-variable" id="toc-redefining-status-as-a-binary-variable" class="nav-link" data-scroll-target="#redefining-status-as-a-binary-variable">Redefining <code>status</code> as a Binary Variable</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#dude-thats-logit" id="toc-dude-thats-logit" class="nav-link" data-scroll-target="#dude-thats-logit">Dude, that’s Logit!</a>
  <ul class="collapse">
  <li><a href="#visualizing-ols-of-categorical-response-variable" id="toc-visualizing-ols-of-categorical-response-variable" class="nav-link" data-scroll-target="#visualizing-ols-of-categorical-response-variable">Visualizing OLS of Categorical Response Variable</a></li>
  <li><a href="#logistic-regressions-with-binomial-family" id="toc-logistic-regressions-with-binomial-family" class="nav-link" data-scroll-target="#logistic-regressions-with-binomial-family">Logistic Regressions with Binomial Family</a></li>
  <li><a href="#binary-dependent-variable" id="toc-binary-dependent-variable" class="nav-link" data-scroll-target="#binary-dependent-variable">Binary Dependent Variable</a></li>
  </ul></li>
  <li><a href="#what-in-the-log-odds" id="toc-what-in-the-log-odds" class="nav-link" data-scroll-target="#what-in-the-log-odds">What in the Log Odds?</a>
  <ul class="collapse">
  <li><a href="#finding-p" id="toc-finding-p" class="nav-link" data-scroll-target="#finding-p">Finding p</a></li>
  <li><a href="#interpreting-coefficients-using-odds-ratio" id="toc-interpreting-coefficients-using-odds-ratio" class="nav-link" data-scroll-target="#interpreting-coefficients-using-odds-ratio">Interpreting Coefficients Using Odds Ratio</a></li>
  <li><a href="#logistic-model-with-2-continuous-variables" id="toc-logistic-model-with-2-continuous-variables" class="nav-link" data-scroll-target="#logistic-model-with-2-continuous-variables">Logistic Model with 2 Continuous Variables</a>
  <ul class="collapse">
  <li><a href="#interpreting-coefficients-using-odds-ratio-1" id="toc-interpreting-coefficients-using-odds-ratio-1" class="nav-link" data-scroll-target="#interpreting-coefficients-using-odds-ratio-1">Interpreting Coefficients using Odds Ratio</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#probabilistic-predictions" id="toc-probabilistic-predictions" class="nav-link" data-scroll-target="#probabilistic-predictions">Probabilistic Predictions</a></li>
  <li><a href="#binary-predictions" id="toc-binary-predictions" class="nav-link" data-scroll-target="#binary-predictions">Binary Predictions</a>
  <ul class="collapse">
  <li><a href="#model-containing-binary-independent-variable" id="toc-model-containing-binary-independent-variable" class="nav-link" data-scroll-target="#model-containing-binary-independent-variable">Model Containing Binary Independent Variable</a></li>
  <li><a href="#interpreting-coefficients-using-odds-ratio-2" id="toc-interpreting-coefficients-using-odds-ratio-2" class="nav-link" data-scroll-target="#interpreting-coefficients-using-odds-ratio-2">Interpreting Coefficients using Odds Ratio</a></li>
  <li><a href="#table-of-binary-predictions" id="toc-table-of-binary-predictions" class="nav-link" data-scroll-target="#table-of-binary-predictions">Table of Binary Predictions</a></li>
  </ul></li>
  <li><a href="#results-summary" id="toc-results-summary" class="nav-link" data-scroll-target="#results-summary">Results Summary</a>
  <ul class="collapse">
  <li><a href="#considering-omitted-variable-bias-ovb" id="toc-considering-omitted-variable-bias-ovb" class="nav-link" data-scroll-target="#considering-omitted-variable-bias-ovb">Considering Omitted Variable Bias (OVB)</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block column-page-left" id="quarto-document-content">




<section id="spatially-distorted-signaling" class="level1">
<h1><strong>Spatially Distorted Signaling:</strong></h1>
<section id="how-opinions-against-wind-infrastructure-delay-our-transition-to-renewable-energy" class="level2">
<h2 class="anchored" data-anchor-id="how-opinions-against-wind-infrastructure-delay-our-transition-to-renewable-energy">How Opinions Against Wind Infrastructure Delay Our Transition to Renewable Energy</h2>
<p>The phenomenon of Spatial Distorted Signalling (SDS) describes the mobilization of minority opinion holders to push back electorally. Leah Stokes (et.al) has explored the SDS phenomenon as a natural experiment in her piece, Electoral Backlash against Climate Policy: A Natural Experiment on Retrospective Voting and Local Resistance to Public Policy (<a href="https://www.jstor.org/stable/24877466">2016</a>). The findings in this paper describe that rural Canadian communities had a greater ability to mobilize and organize political pushback against majority chair holders in parliament after the passing of legislation that incentivized the development of wind infrastructure.</p>
<p>Since then, Leah has navigated the nuances of varying percentiles in races, political affiliation (particularly the % precinct gop voting share), the scale and size of the project, as well as, the volume of local mobilization in her research, Replication Data for: Prevalence and predictors of wind energy opposition in North America (<a href="https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/LE2V0R">2023</a>).&nbsp;</p>
<p>I am hoping to reproduce these naturally observed outcomes with the US Wind Data and assess the relationship of population density and the project status of wind plants. Analysis of these relationships could provide insight into understanding the scaling effect that local resistance has on spatially distorted signalling in relation to wind infrastructure projects and and sustainable climate policy.</p>
<p>The data source that was utilized in this project, <a href="https://dataverse.harvard.edu/file.xhtml?fileId=7339850&amp;version=1.0">US Wind Data</a>, focuses on the public stance on wind infrastructure for census tract regions within a 3 km buffer zone of a wind plant. It contains categorical variables, binary variables, continuous socioeconomic factors such as % of races, % precinct political gop affiliated voting share, mobilization tactics, and more. Data is associated with the <em>Replication Data for: Prevalence and predictors of wind energy opposition in North America</em>, <a href="https://doi.org/10.7910/DVN/LE2V0R">doi</a> Harvard Dataverse, V1, 2023. The collaborators on that project include: Stokes, Leah; Franzblau, Emma; Lovering, Jessica R.; Miljanich, Chris. Leah Stokes and her awesome team gathered all of this information from American Wind Association (awea), operational, Columbia Sabin Center (columbia).</p>
<section id="main-takeaways" class="level3">
<h3 class="anchored" data-anchor-id="main-takeaways">Main Takeaways:</h3>
<ul>
<li><p>Intuitively as expected, a single unit increase in population density is associated with a minor increase in the odds ratio of a wind plant operating. Our models also described that for each single unit increase in median income, there is a decrease in the odds ratio that a wind plant is operational. Similarly, this is seen with anti wind infrastructure opinion holders.</p></li>
<li><p>Although our p-values each of our models provided p-values for our coefficients that are hold because they are above the significance level of 0.05. We cannot make any definitive assumptions about our logistic regression models because there is insufficient evidence inspecting the influential effects of omitted variables bias and a lack of data for regions with non-operational wind plants.</p></li>
<li><p>If given the opportunity, I would expand the dataset to include any more possible non-operational wind plants and explore in greater detail how exogenous our variables are and determine which values are likely interacting, to produce the best model fit.</p></li>
</ul>
</section>
<section id="loading-libraries" class="level3">
<h3 class="anchored" data-anchor-id="loading-libraries">Loading Libraries</h3>
<p>The following libraries were selected based on their functionality and ability to optimize our data for mapping.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Loading Libraries</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)        </span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)               </span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(cowplot)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(spData)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(raster)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggspatial)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(prettymapr)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggmap)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(naniar)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gt)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tmap)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(terra)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stars)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(devtools)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(maptiles)</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(smoothr)       </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
</section>
<section id="read-in-the-data" class="level1">
<h1>Read in the Data</h1>
<section id="u.s.-wind-data" class="level4">
<h4 class="anchored" data-anchor-id="u.s.-wind-data">U.S. Wind Data</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># reading in &amp; storing data</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>wind_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"../data/wind_data_usa.csv"</span>)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="initial-visualization-of-the-data" class="level1">
<h1>Initial Visualization of the Data</h1>
<p>Below we can see the spatial scope of our data being considered. Each bubble represents a wind power project within the United States from 2010-2016.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># First visual of the U.S. wind data provided by the geometry points</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>wind_plants <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(wind_sf) <span class="sc">+</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotation_map_tile</span>(<span class="at">type =</span> <span class="st">"osm"</span>) <span class="sc">+</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">col =</span> <span class="st">'darkgreen'</span>,</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">alpha =</span> <span class="fl">0.5</span>,</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>          <span class="at">size =</span> <span class="dv">3</span>) </span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>wind_plants</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="SDS_Wind_Infrastructure-blog_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="linear-regression-models" class="level1">
<h1>Linear Regression Models</h1>
<section id="variables-of-interest" class="level3">
<h3 class="anchored" data-anchor-id="variables-of-interest">Variables of Interest:</h3>
<p>These variables focus more on regionally dependent factors that intuitively seem to have an impact on mobilization variables we don’t have time to cover in this project. We’ll be working with a mix of discrete and continuous data, so there some wrangling will be necessary to run the regressions we’re interested in.</p>
<table class="table">
<colgroup>
<col style="width: 25%">
<col style="width: 75%">
</colgroup>
<thead>
<tr class="header">
<th>Name</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>status</td>
<td>Describes the project operating status. In this study, we have converted it into a binary variable: 1 is operating, 0 is not_operating.</td>
</tr>
<tr class="even">
<td>pop_den</td>
<td>Tract-level 2010 census data for population density (per mi^2)</td>
</tr>
<tr class="odd">
<td>med_inc</td>
<td>Tract-level 2010 census data for median income</td>
</tr>
<tr class="even">
<td>is_anti_wind</td>
<td>Binary measure of wind opposition</td>
</tr>
</tbody>
</table>
</section>
<section id="determining-variable-assignments-for-ols" class="level2">
<h2 class="anchored" data-anchor-id="determining-variable-assignments-for-ols">Determining Variable Assignments for OLS</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(wind_sf<span class="sc">$</span>status)     <span class="co"># displays unique values in this</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Operating"                    "Cancelled"                   
[3] "Out of service (temporarily)" "Standby"                     
[5] "Decommissioned"               "Operating | Decommissioned"  
[7] NA                            </code></pre>
</div>
</div>
<section id="redefining-status-as-a-binary-variable" class="level3">
<h3 class="anchored" data-anchor-id="redefining-status-as-a-binary-variable">Redefining <code>status</code> as a Binary Variable</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># creating two categories: operating &amp; not_operating</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="co"># We are removing 'Operating | Decommissioned' because it skews the data</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>unwanted_status <span class="ot">&lt;-</span> <span class="st">"Operating | Decommissioned"</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>replacement_status <span class="ot">&lt;-</span> <span class="st">"Uncertain Status"</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>wind_sf<span class="sc">$</span>status[wind_sf<span class="sc">$</span>status<span class="sc">==</span> unwanted_status]<span class="ot">&lt;-</span><span class="st">"Uncertain Status"</span>  </span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="co"># were we successful ?</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="co">#unique(wind_sf$status)     # displays unique values in this</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a><span class="co"># cleaning out NAs for OLS</span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>wind_sf <span class="ot">&lt;-</span> wind_sf <span class="sc">%&gt;%</span></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">is.na</span>(status) <span class="sc">==</span> <span class="st">'FALSE'</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">is.na</span>(is_anti_wind) <span class="sc">==</span> <span class="st">'FALSE'</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">is.na</span>(pop_den) <span class="sc">==</span> <span class="st">'FALSE'</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">is.na</span>(med_inc) <span class="sc">==</span> <span class="st">'FALSE'</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">is.na</span>(median_age) <span class="sc">==</span> <span class="st">'FALSE'</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">is.na</span>(n_turbs) <span class="sc">==</span> <span class="st">'FALSE'</span>)</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a><span class="co"># were we successful ?</span></span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a><span class="co">#unique(wind_sf$status)     # displays unique values in this</span></span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a><span class="co"># if_else preserves the data type but replaces unwanted values</span></span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>wind_us <span class="ot">&lt;-</span> wind_sf <span class="sc">%&gt;%</span> </span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">status =</span> <span class="fu">if_else</span>(</span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>    status <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">'Cancelled'</span>, <span class="st">'Out of service (temporarily)'</span>, <span class="st">'Standby'</span>, <span class="st">'Decommissioned'</span>, <span class="st">'Uncertain Status'</span>), <span class="st">'not_operating'</span>,</span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a>    <span class="st">'operating'</span>) </span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a><span class="co"># are our only outputs "operating" and "not_operating"?</span></span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a><span class="co">#print(unique(wind_us$status))</span></span>
<span id="cb6-31"><a href="#cb6-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-32"><a href="#cb6-32" aria-hidden="true" tabindex="-1"></a><span class="co"># status as factor and reassigned values</span></span>
<span id="cb6-33"><a href="#cb6-33" aria-hidden="true" tabindex="-1"></a>wind_us <span class="ot">&lt;-</span> wind_us <span class="sc">%&gt;%</span> </span>
<span id="cb6-34"><a href="#cb6-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">status =</span> <span class="fu">case_when</span>(status <span class="sc">==</span> <span class="st">"operating"</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb6-35"><a href="#cb6-35" aria-hidden="true" tabindex="-1"></a>            status <span class="sc">==</span> <span class="st">"not_operating"</span> <span class="sc">~</span> <span class="dv">0</span>))</span>
<span id="cb6-36"><a href="#cb6-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-37"><a href="#cb6-37" aria-hidden="true" tabindex="-1"></a><span class="co"># are our only outputs 0 or 1?</span></span>
<span id="cb6-38"><a href="#cb6-38" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">unique</span>(wind_us<span class="sc">$</span>status))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1 0</code></pre>
</div>
</div>
<p>Binary variable will be <code>status</code> variable: <code>opertating</code> is 1, and <code>not_operating</code> will be 0.</p>
</section>
</section>
</section>
<section id="dude-thats-logit" class="level1">
<h1>Dude, that’s Logit!</h1>
<p>Our model below is describing the linear regression for the effect of population density on wind project operating status. This is really a formality to demonstrate why OLS is not the correct approach for interpreting our relationships of interest.</p>
<section id="visualizing-ols-of-categorical-response-variable" class="level3">
<h3 class="anchored" data-anchor-id="visualizing-ols-of-categorical-response-variable">Visualizing OLS of Categorical Response Variable</h3>
<p>Our initial visualization demonstrates a correlation between smaller population density and wind infrastructure plants operating. This is likely associated with weight placed on voters in regions with smaller demographics. Local mobilization of minority opinion holders in these regions have a greater availability to push back against policymakers. However, this visual does not encapsulate all of the necessary information required to determine this with full certainty. Our data set has poor availability for non-operating infrastructure, these are being treated as outliers.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="SDS_Wind_Infrastructure-blog_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
    0.143     4.309    12.493   181.484    40.394 13940.515 </code></pre>
</div>
</div>
</section>
<section id="logistic-regressions-with-binomial-family" class="level3">
<h3 class="anchored" data-anchor-id="logistic-regressions-with-binomial-family">Logistic Regressions with Binomial Family</h3>
<p>Our model below is describing the linear &amp; logistic regressions for the effect of population density on wind project operating status. This visual is very interesting and definitely explains why the <span class="math inline">\(R^2\)</span> value is only giving values in the 0.9 range. Since our data contains a significant number of <code>operating</code> wind plants for a wide range of population densities, the regression model is producing a fit according to the <code>operating</code> status. The values in the <code>not_opertating</code> status appear to be considered similar to that of an outlier.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="SDS_Wind_Infrastructure-blog_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="binary-dependent-variable" class="level3">
<h3 class="anchored" data-anchor-id="binary-dependent-variable">Binary Dependent Variable</h3>
<p><span class="math display">\[\text{status} = \beta_0 + \beta_1 \text{pop_den}\_i + \varepsilon_i\]</span></p>
<ul>
<li><p>Our summary table describes a null deviance <code>362.60</code>.(<code>1178 df</code>) and residual deviance <code>362.22</code> (<code>1177 df</code>).</p></li>
<li><p>A p-value of <code>0.593</code> for <span class="math inline">\(\beta_1\)</span>, is greater than the significant value of 0.05, therefore, the model hypothesis that operation status is influenced by population density holds.</p></li>
<li><p>However, I am still not convinced there isn’t a correlation shared with another factor, so let’s explore how our numbers change as we incorporate more variables into our equation later on.</p></li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = status ~ pop_den, family = "binomial", data = wind_us)

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) 3.2721930  0.1623175  20.159   &lt;2e-16 ***
pop_den     0.0001793  0.0003356   0.534    0.593    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 362.60  on 1178  degrees of freedom
Residual deviance: 362.22  on 1177  degrees of freedom
AIC: 366.22

Number of Fisher Scoring iterations: 6</code></pre>
</div>
</div>
</section>
</section>
<section id="what-in-the-log-odds" class="level1">
<h1>What in the Log Odds?</h1>
<p>So far, we haven’t been able to gather very much useful information to describe our model predictions. Since we’re working with a binomial family, the p-values produced in the <code>glm()</code> need to be further extrapolated before they may be used to interpret our model.</p>
<p>Our model that we just fit tells us that:</p>
<section id="logitplog-p-1pβ0β1xε" class="level4">
<h4 class="anchored" data-anchor-id="logitplog-p-1pβ0β1xε"><span class="math display">\[logit(p)=log( p / 1−p)=β0+β1x+ε\]</span></h4>
<p>so then, to solve for p:</p>
<p><span class="math display">\[p̂=e^(β0+β1x1+eβ0+β1x)\]</span></p>
<p>Alternatively, we’re going to solve for p using&nbsp;<span class="math inline">\(R^2\)</span> because that looks gross. The&nbsp;<code>uniroot</code>&nbsp;function searches over the provided interval to find the zero value of the function provided. We pass the expression that should equal zero, and it finds us the p that ensures it equals zero.</p>
</section>
<section id="finding-p" class="level2">
<h2 class="anchored" data-anchor-id="finding-p">Finding p</h2>
<p>Utilizing the funky relationship described above, we can solve for a range of p values using <span class="math inline">\(R^2\)</span>. We’re curious about the probability of <code>operating</code> wind plants for Population Density at <code>20,000</code>, <code>6,000</code>, and <code>600.</code></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9989509</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9872347</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.967067</code></pre>
</div>
</div>
<p>Manually computing the probability for different outcomes is tedious and inefficient. To improve this, we can make a table containing the odds ratio of how often a binary event occurs.</p>
</section>
<section id="interpreting-coefficients-using-odds-ratio" class="level2">
<h2 class="anchored" data-anchor-id="interpreting-coefficients-using-odds-ratio">Interpreting Coefficients Using Odds Ratio</h2>
<p>To better interpret this relationship, we are going to change the scale of the variable on the y-axis. Now, we will be considering the odds, rather than the probability. While these two concepts are often conflated, they are not the same[<a href="https://tcarleton.github.io/EDS-222-stats/labs/06-week-six/week-6-lab-answers.html">2</a>]. They are however, related by the simple formula below.</p>
<p>The&nbsp;<strong>odds</strong>&nbsp;of a binary event are the ratio of how often it happens, to how often it doesn’t happen.</p>
<p><span class="math inline">\(odds(p̂)=p̂1−p̂=exp(β̂0+β̂1⋅x)\)</span></p>
<p>We’re going create an&nbsp;<code>odds_hat</code>&nbsp;variable for predicted odds. The ratio of the odds <em>after</em> a single unit increase in x to the odds <em>before</em> that one unit change is equal to&nbsp;eβ1.&nbsp;<strong>Notice this doesn’t depend on</strong> x&nbsp;anymore! Therefore, it’s a useful interpretation of coefficients.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>status_popden_predicted_odds <span class="ot">&lt;-</span>  status <span class="sc">%&gt;%</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>(<span class="at">type.predict =</span> <span class="st">"response"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">y_hat =</span> .fitted) <span class="sc">%&gt;%</span> </span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">odds_hat =</span> y_hat <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">-</span> y_hat)) <span class="sc">%&gt;%</span> </span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gt</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This is an “odds ratio”, meaning we care about how this number differs from 1. If it’s greater than 1, then the odds increase when&nbsp;x&nbsp;increases. Conversely, if it’s less than 1, then the odds decrease.</p>
<ul>
<li>By how much does our model predict that the odds of <code>operating status</code> will change with each additional unit increase in population density?</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(status1<span class="sc">$</span>coefficients[<span class="dv">2</span>,<span class="st">'Estimate'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.000179</code></pre>
</div>
</div>
<p><strong>Answer:</strong>&nbsp;Our model estimates that one unit increase in population density is associated with a change in the odds ratio of <span class="math inline">\(e^(0.0001793) =1.000179\)</span>, or a 1.79e-04% increase in the odds of wind plant having an <code>operating</code> status.</p>
</section>
<section id="logistic-model-with-2-continuous-variables" class="level2">
<h2 class="anchored" data-anchor-id="logistic-model-with-2-continuous-variables">Logistic Model with 2 Continuous Variables</h2>
<p><span class="math display">\[\text{status}\ = \beta_0 + \beta_1 \text{pop_den}\_i + \beta_2 \text{med_inc} + \varepsilon_i\]</span></p>
<ul>
<li><p>Our summary table describes a null deviance 362.60.(1178 df) and residual deviance 359.84 (1176 df).</p></li>
<li><p>Additionally, it provides a p-value of 0.511 for <span class="math inline">\(\beta_1\)</span>, indicating that the hypothesis here is accepted because it is greater than the significant value of 0.05.</p></li>
<li><p>The p-value of <span class="math inline">\(\beta_2\)</span>, 0.957 is acceptable because it is above range of the significant value.</p></li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = status ~ pop_den + med_inc, family = "binomial", 
    data = wind_us)

Coefficients:
              Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  4.028e+00  4.950e-01   8.138 4.03e-16 ***
pop_den      2.477e-04  3.776e-04   0.656   0.5118    
med_inc     -1.497e-05  8.988e-06  -1.666   0.0957 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 362.60  on 1178  degrees of freedom
Residual deviance: 359.84  on 1176  degrees of freedom
AIC: 365.84

Number of Fisher Scoring iterations: 6</code></pre>
</div>
</div>
<section id="interpreting-coefficients-using-odds-ratio-1" class="level3">
<h3 class="anchored" data-anchor-id="interpreting-coefficients-using-odds-ratio-1">Interpreting Coefficients using Odds Ratio</h3>
<p>It’s important to remember that we still need to exponentiate our estimated values in order to obtain our p-values. We’re here to break the status quo of OLS and train our brains to interpret logistic regressions using the Odds Ratio.</p>
<p>By including the median income variable in our model and exponentiating the coefficients, we see a huge effect. Areas with an increase in population density observed an increase in their odds of having active wind infrastructure by a factor of 2.48e-04% when controlling the median income. However, the odds of operating status decrease by 1.5e-05 for each average unit increase in median income.</p>
<section id="logitplog-p-1pβ0β1xε-1" class="level4">
<h4 class="anchored" data-anchor-id="logitplog-p-1pβ0β1xε-1"><span class="math display">\[logit(p)=log( p / 1−p)=β0+β1x+ε\]</span></h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># beta1 estimation exponentiated</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(status2<span class="sc">$</span>coefficients[<span class="dv">2</span>,<span class="st">'Estimate'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.000248</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># beta2 estimation exponentiated</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">exp</span>(status2<span class="sc">$</span>coefficients[<span class="dv">3</span>,<span class="st">'Estimate'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.497159e-05</code></pre>
</div>
</div>
</section>
</section>
</section>
</section>
<section id="probabilistic-predictions" class="level1">
<h1>Probabilistic Predictions</h1>
<p>We are going to making some probability predictions using out-of-sample predictions using the <code>type.predict</code> argument set as “response”, to retrieve fitted values on the familiar probability scale.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># probability scale</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>probability_predictions <span class="ot">&lt;-</span> <span class="fu">augment</span>(status_2, <span class="at">type.predict =</span> <span class="st">"response"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gt</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>For example, our model predicts the odds that an area with a population density of 124 and a median income of 46,094 and would have an operating wind plant is ~97%.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>exploring_model <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">pop_den =</span> <span class="dv">124</span>, <span class="at">med_inc =</span> <span class="dv">46094</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(status_2, <span class="at">newdata =</span> exploring_model, <span class="at">type.predict =</span> <span class="st">"response"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gt</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div id="kymroqyynm" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#kymroqyynm table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#kymroqyynm thead, #kymroqyynm tbody, #kymroqyynm tfoot, #kymroqyynm tr, #kymroqyynm td, #kymroqyynm th {
  border-style: none;
}

#kymroqyynm p {
  margin: 0;
  padding: 0;
}

#kymroqyynm .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#kymroqyynm .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#kymroqyynm .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#kymroqyynm .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#kymroqyynm .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#kymroqyynm .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#kymroqyynm .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#kymroqyynm .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#kymroqyynm .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#kymroqyynm .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#kymroqyynm .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#kymroqyynm .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#kymroqyynm .gt_spanner_row {
  border-bottom-style: hidden;
}

#kymroqyynm .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#kymroqyynm .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#kymroqyynm .gt_from_md > :first-child {
  margin-top: 0;
}

#kymroqyynm .gt_from_md > :last-child {
  margin-bottom: 0;
}

#kymroqyynm .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#kymroqyynm .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#kymroqyynm .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#kymroqyynm .gt_row_group_first td {
  border-top-width: 2px;
}

#kymroqyynm .gt_row_group_first th {
  border-top-width: 2px;
}

#kymroqyynm .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#kymroqyynm .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#kymroqyynm .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#kymroqyynm .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#kymroqyynm .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#kymroqyynm .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#kymroqyynm .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#kymroqyynm .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#kymroqyynm .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#kymroqyynm .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#kymroqyynm .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#kymroqyynm .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#kymroqyynm .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#kymroqyynm .gt_left {
  text-align: left;
}

#kymroqyynm .gt_center {
  text-align: center;
}

#kymroqyynm .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#kymroqyynm .gt_font_normal {
  font-weight: normal;
}

#kymroqyynm .gt_font_bold {
  font-weight: bold;
}

#kymroqyynm .gt_font_italic {
  font-style: italic;
}

#kymroqyynm .gt_super {
  font-size: 65%;
}

#kymroqyynm .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#kymroqyynm .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#kymroqyynm .gt_indent_1 {
  text-indent: 5px;
}

#kymroqyynm .gt_indent_2 {
  text-indent: 10px;
}

#kymroqyynm .gt_indent_3 {
  text-indent: 15px;
}

#kymroqyynm .gt_indent_4 {
  text-indent: 20px;
}

#kymroqyynm .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="pop_den">pop_den</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="med_inc">med_inc</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id=".fitted">.fitted</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="pop_den" class="gt_row gt_right">124</td>
<td headers="med_inc" class="gt_row gt_right">46094</td>
<td headers=".fitted" class="gt_row gt_right">0.9667131</td></tr>
  </tbody>
  
  
</table>
</div>
</div>
</div>
</section>
<section id="binary-predictions" class="level1">
<h1>Binary Predictions</h1>
<section id="model-containing-binary-independent-variable" class="level3">
<h3 class="anchored" data-anchor-id="model-containing-binary-independent-variable">Model Containing Binary Independent Variable</h3>
<p><span class="math display">\[\text{status}\ = \beta_0 + \beta_1 \text{pop_den}\_i + + \beta_2 \text{is_anti_wind} + \varepsilon_i\]</span></p>
<ul>
<li><p>Our summary table describes a null deviance 362.60.(1178 df) and residual deviance 289.8 (1175 df).</p></li>
<li><p>Additionally, it provides a p-value of 0.819 for <span class="math inline">\(\beta_1\)</span>, indicating that the hypothesis here is accepted because it is drastically smaller than the significant value of 0.05.</p></li>
<li><p>The p-value of <span class="math inline">\(\beta_2\)</span>, 0.668 is acceptable because it is within range of the significant value.</p></li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = status ~ pop_den + is_anti_wind, family = "binomial", 
    data = wind_us)

Coefficients:
               Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)   4.467e+00  3.076e-01  14.524  &lt; 2e-16 ***
pop_den       7.565e-05  3.304e-04   0.229    0.819    
is_anti_wind -2.798e+00  3.612e-01  -7.746 9.47e-15 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 362.60  on 1178  degrees of freedom
Residual deviance: 292.13  on 1176  degrees of freedom
AIC: 298.13

Number of Fisher Scoring iterations: 7</code></pre>
</div>
</div>
</section>
<section id="interpreting-coefficients-using-odds-ratio-2" class="level3">
<h3 class="anchored" data-anchor-id="interpreting-coefficients-using-odds-ratio-2">Interpreting Coefficients using Odds Ratio</h3>
<p>So, after some manipulation, we find that the odds ratio gives us some good information.</p>
<ul>
<li>Areas with an increase in population density observed an increase in their odds of having active wind infrastructure by a factor of 7.6e-05% when controlling the local opinion on wind constant. However, the odds of operating status decrease by ~7% for areas that identify as anti wind infrastructure.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># beta1 estimation exponentiated</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(status3<span class="sc">$</span>coefficients[<span class="dv">2</span>,<span class="st">'Estimate'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.000076</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># beta2 estimation exponentiated</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">exp</span>(status3<span class="sc">$</span>coefficients[<span class="dv">3</span>,<span class="st">'Estimate'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9390681</code></pre>
</div>
</div>
</section>
<section id="table-of-binary-predictions" class="level2">
<h2 class="anchored" data-anchor-id="table-of-binary-predictions">Table of Binary Predictions</h2>
<p>What do these predictions tell us?</p>
<p>Well, they lend us some insight into whether or not we can definitively predict the status outcome of a region depending on their population density and position on wind opposition. They additionally provide the model fit (<span class="math inline">\(R^2\)</span>) value associated with the predicted value.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>status_binary <span class="ot">&lt;-</span> <span class="fu">augment</span>(status_3, <span class="at">type.predict =</span> <span class="st">"response"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">operating_hat =</span> <span class="fu">round</span>(.fitted))</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>binary_predictions <span class="ot">&lt;-</span> status_binary <span class="sc">%&gt;%</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(status, pop_den, is_anti_wind, .fitted, operating_hat) <span class="sc">%&gt;%</span> </span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gt</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="results-summary" class="level1">
<h1>Results Summary</h1>
<p>Intuitively as expected, a single unit increase in population density is associated with a minor increase in the odds ratio of a wind plant operating. Our models also described that for each single unit increase in median income, there is a decrease in the odds ratio that a wind plant is operational. Similarly, this is seen with anti wind infrastructure opinion holders.</p>
<p>Although our p-values each of our models provided p-values for our coefficients that are hold because they are above the significance level of 0.05. We cannot make any definitive assumptions about our logistic regression models because there is insufficient evidence inspecting the influential effects of omitted variables bias and a lack of data for regions with non-operational wind plants.</p>
<p>If given the opportunity, I would expand the dataset to include any more possible non-operational wind plants and explore in greater detail how exogenous our variables are and determine which values are likely interacting, to produce the best model fit.</p>
<section id="considering-omitted-variable-bias-ovb" class="level3">
<h3 class="anchored" data-anchor-id="considering-omitted-variable-bias-ovb">Considering Omitted Variable Bias (OVB)</h3>
<p>Neglecting additional variables without testing is bad practice. Exogeneity is a very difficult OLS assumption to uphold – alongside a normal distribution of the error mean. A means to determine relationships between variables is running various linear regression models and comparing the <span class="math inline">\(R^2\)</span> value. In this project, we focused our attention on the why OLS was not the analysis method of choice for our relationships of interest. In the instance of logistic regression, a log odds ratio must be taken to interpret each individual variable. There is a strong possibility that the models utilized in this project are not exogenous and require deeper analysis to determine the impact of underlining influences.<br>
</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
 Copyright 2023, Sofia Ingersoll
  </li>  
</ul>
    </div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/saingersoll">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>



</body></html>